# Generated by Django 4.1.5 on 2023-01-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_linkmapping_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmapping',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
