# Generated by Django 4.1.5 on 2023-01-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_linkmapping_click_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmapping',
            name='click_count',
        ),
    ]
